---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-truststore-mgr-operator
spec:
  selector:
    matchLabels:
      control-plane: ibm-truststore-mgr
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: ibm-truststore-mgr
    spec:
      serviceAccountName: ibm-truststore-mgr-operator
      imagePullSecrets:
        - name: ibm-entitlement
      containers:
        - name: manager
          image: "{{ICR_CPOPEN}}/ibm-truststore-mgr:{{VERSION}}"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 512Mi
      terminationGracePeriodSeconds: 10
